export const TOGGLE_BLUR = 'TOGGLE_BLUR';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const SET_ORDERS = 'SET_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_ORDER_PRINT_STATUS = 'UPDATE_ORDER_PRINT_STATUS';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHOOSE_COUNTRY = 'CHOOSE_COUNTRY';
export const UPDATE_ORDER_COUNT = 'UPDATE_ORDER_COUNT';
export const REDUCE_NEW_ORDER_COUNT = 'REDUCE_NEW_ORDER_COUNT';

export const UPDATE_DRIVER_ASSIGNED_COUNT = 'UPDATE_DRIVER_ASSIGNED_COUNT';

export const UPDATE_ORDER_BADGE_COUNT = 'UPDATE_ORDER_BADGE_COUNT';

export const SET_SHOPS = 'SET_SHOPS';
export const SET_EMIRATES = 'SET_EMIRATES';

export const UPDATE_EDIT_SHOP_DATA = 'UPDATE_EDIT_SHOP_DATA';

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const REFRESH_PRODUCT = 'REFRESH_PRODUCT';
