import {StyleSheet} from 'react-native';
import {screenwidth, theme_color} from '../../mutils';
import {myfonts} from '../../assets/Fonts';

const styles = StyleSheet.create({
	plusIcon: {
		width: 16,
		height: 16,
		marginLeft: 5,
		marginVertical: 4,
	},
	createUser: {
		flexDirection: 'row',
		marginRight: 'auto',
		marginLeft: 'auto',
	},
	mh16: {
		marginHorizontal: 16,
		marginBottom: 8,
	},
	mainTxt: {
		fontFamily: 'Inter-Regular',
		fontSize: 16,
		//: 500,
		letterSpacing: 0,
		textAlign: 'left',
		marginHorizontal: 16,
		color: '#475569',
	},
	input: {
		width: screenwidth - 64,
		height: 42,
		borderRadius: 6,
		borderWidth: 1,
		borderColor: '#E2E8F0',
		marginVertical: 16,
		backgroundColor: 'white',
	},
	orderTxt: {
		color: '#1E293B',
		fontFamily: 'Inter-Bold',
		fontSize: 18,
		marginTop: 16,
		marginBottom: 24,
		marginLeft: 32,
		//: 600,
		//line-height: 27px;
		//letter-spacing: 0px;
		textAlign: 'left',
	},
	itemBase: {
		borderRadius: 8,
		borderWidth: 1,
		borderColor: '#E2E8F0',
		marginBottom: 16,
	},
	firstrow: {
		borderTopEndRadius: 8,
		borderTopLeftRadius: 8,
		flex: 1,
		flexDirection: 'row',
		backgroundColor: '#FAFAFA',
		//padding: 16,
	},
	secondrow: {
		flex: 1,
		flexDirection: 'row',
		backgroundColor: 'white',
		// padding: 16,
	},
	thirdrow: {
		flex: 1,
		flexDirection: 'row',
		backgroundColor: '#FAFAFA',
		// borderBottomRightRadius: 8,
		// borderBottomLeftRadius: 8,
		borderBottomColor: '#E2E8F0',
		borderBottomWidth: 0,
		//padding: 16,
	},
	fourthrow: {
		//padding: 16,
		flex: 1,
		flexDirection: 'row',
		backgroundColor: 'white',
	},
	fifthrow: {
		flex: 1,
		flexDirection: 'row',
		backgroundColor: '#FAFAFA',
		//padding: 16,
	},
	lastrow: {
		flex: 1,
		flexDirection: 'row',
		backgroundColor: 'white',
		borderBottomRightRadius: 8,
		borderBottomLeftRadius: 8,
		borderBottomColor: '#E2E8F0',
		borderBottomWidth: 0,
		// padding: 16,
	},

	itemMain: {
		borderRadius: 8,
		borderWidth: 1,
		borderColor: '#E2E8F0',
		marginBottom: 16,
	},
	item: {
		flex: 0.5,
		padding: 16,
	},
	item_details: {
		flex: 0.25,
		paddingVertical: 4.5,
		paddingHorizontal: 6,
	},

	itemHeader: {
		color: '#334155',
		fontFamily: 'Inter-Bold',
		fontSize: 12,
		//: 600,
		marginHorizontal: 8,
		paddingVertical: 6.5,

		lineHeight: 18,
		letterSpacing: 0,
	},
	itemValue: {
		color: '#475569',
		fontFamily: 'Inter-Medium',
		fontSize: 12,
		//: 400,
		paddingVertical: 6.5,
		marginHorizontal: 8,
		lineHeight: 18,
		letterSpacing: 0,
	},
	orderItemView: {
		marginHorizontal: 8,
	},
	container: {backgroundColor: 'white', borderRadius: 8, marginBottom: 16},
	btn: {
		paddingVertical: 12,
		paddingHorizontal: 24,
		height: 48,
		backgroundColor: theme_color,
		borderRadius: 6,
	},
	btnTxt: {
		color: 'white',
		marginRight: 'auto',
		marginLeft: 'auto',
		fontFamily: 'Inter-Regular',
		fontSize: 16,
		//: 500,
	},
	noteMain: {
		marginBottom: 16,
		backgroundColor: 'white',
		padding: 16,
		borderRadius: 8,
		margin: 2,
	},
	title: {
		color: '#334155',
		fontFamily: 'Inter-Bold',
		fontSize: 16,
		//: 500,
		textAlign: 'left',
		marginBottom: 8,
	},
	mainView: {flex: 1, flexDirection: 'row', marginTop: 16, marginBottom: 24},
	leftView: {
		flex: 0.5,
		flexDirection: 'column',
		marginLeft: 16,
		marginRight: 16,
	},
	rightView: {flex: 0.5, flexDirection: 'column', marginRight: 16},
	mainTxt: {
		fontFamily: 'Inter-Medium',
		fontSize: 16,
		//: 500,
		letterSpacing: 0,
		textAlign: 'left',
		//marginHorizontal: 16,
		color: '#334155',
		marginBottom: 4,
	},
	subTxt: {
		fontFamily: myfonts.Regular,
		fontSize: 12,
		//: 400,
		textAlign: 'left',
		//marginHorizontal: 16,
		color: '#64748B',
	},
	thirtyMinutes: {
		fontFamily: myfonts.Regular,
		fontSize: 14,
		//: 500,
		lineHeight: 21,
		letterSpacing: 0,
		textAlign: 'left',
		color: '#334155',
		marginRight: 4,
		marginLeft: 4,
	},
	acceptBtn: {
		backgroundColor: '#334155',
		width: 109,
		color: 'white',
		paddingVertical: 8,
		paddingHorizontal: 24,
		//margin: 8,
		borderRadius: 6,
	},
});
export default styles;
