import {StyleSheet} from 'react-native';
import {theme_color} from '../../mutils';
import myColors from '../../styles/myColors';
import {myfonts} from '../../assets/Fonts';

const timeStyles = StyleSheet.create({
	actionBtn: {
		width: 77,
		height: 36,
		paddingVertical: 10,
		paddingHorizontal: 8,
		borderRadius: 4,
	},
	actionBtnTxt: {
		// fontFamily: 'Roboto',
		fontSize: 14,
		//: 500,
		lineHeight: 16,
		letterSpacing: 1.25,
		textAlign: 'center',
		color: theme_color,
	},
	subTxt: {
		marginTop: 7,
		fontFamily: myfonts.Regular,
		fontSize: 12,
		//: 400,
		lineHeight: 16,
		letterSpacing: 0.4000000059604645,
		textAlign: 'left',
		color: myColors.slate500,
	},
	columnTxt: {
		fontFamily: myfonts.Regular,
		fontSize: 14,
		//: 500,
		lineHeight: 16,
		letterSpacing: 1.25,
		textAlign: 'center',
		color: myColors.slate500,
	},
	subColumn: {
		width: 52,
		height: 40,
		paddingBottom: 0,
		paddingHorizontal: 0,
		alignItems: 'center',
		justifyContent: 'center',
	},
	column: {
		flexDirection: 'column',
		width: 52,
		height: 80,
		borderRadius: 4,
		borderWidth: 1,
		borderColor: myColors.slate200,
		marginLeft: 16,
	},
	inputfield: {
		width: '100%',
		height: '100%',
	},
	hourTxt: {
		fontFamily: myfonts.Regular,
		fontSize: 40,
		//	//: 400,
		// lineHeight: 64,
		letterSpacing: 0,
		textAlign: 'center',
		color: myColors.slate700,
	},
	hour: {
		width: 96,
		//flex: 0.5,
		height: 80,
		borderRadius: 4,
		backgroundColor: myColors.slate100,
		paddingVertical: 8,
		alignItems: 'center',
		justifyContent: 'center',
	},
	enterTxt: {
		fontFamily: myfonts.Regular,
		fontSize: 10,
		//: 500,
		lineHeight: 16,
		letterSpacing: 1.5,
		textAlign: 'left',
		color: myColors.slate500,
	},

	enterView: {
		height: 16,
		paddingVertical: 0,
		paddingHorizontal: 10,
		margin: 10,
		marginBottom: 10,
	},
	timeView: {
		minHeight: 100,
		paddingTop: 16,
		paddingBottom: 16,
		paddingHorizontal: 0,
		borderRadius: 6,
		borderWidth: 1,
		marginBottom: 24,
		borderColor: myColors.slate200,
		//elevation: 1,
		shadowRadius: 1,
		marginTop: 24,
	},
	input: {
		marginBottom: 16,
		flexDirection: 'row',
	},
	timeTxt: {
		marginLeft: 16,
		marginVertical: 8,
	},
	closeImg: {
		width: 24,
		height: 24,
		left: 6.75,
	},
	img: {
		width: 24,
		height: 24,
		marginRight: 16,
		marginVertical: 9,
		right: 0,
		position: 'absolute',
	},
	modalView: {
		backgroundColor: 'white',
		borderRadius: 8,
		padding: 35,
		alignItems: 'center',
		shadowColor: theme_color,
		shadowOpacity: 1,
		elevation: 4,
		marginBottom: 40,
	},
});

export default timeStyles;
