import {StyleSheet} from 'react-native';
import {screenHeight, screenwidth, theme_color} from '../../mutils';
import {myfonts} from '../../assets/Fonts';
import myColors from '../../styles/myColors';

const giftstyles = StyleSheet.create({
	resetTxt: {
		color: myColors.slate500,
		marginRight: 'auto',
		marginLeft: 'auto',
	},
	resetBtn: {
		backgroundColor: 'transparent',
		borderWidth: 1,
		borderColor: myColors.slate500,
		marginHorizontal: 0,
		height: 48,
		marginVertical: 4,
	},
	smallTxt1: {
		fontFamily: myfonts.Regular,
		fontSize: 12,
		//: 500,
		lineHeight: 18,
		textAlign: 'center',
	},
	smallTxt: {
		fontFamily: myfonts.Regular,
		fontSize: 12,
		//: 500,
		lineHeight: 18,
		textAlign: 'center',
	},
	subheader: {
		textAlign: 'left',
		fontFamily: 'Inter-Regular',
		fontSize: 14,
		//: 400,
		lineHeight: 21,
		marginBottom: 24,
		color: '#475569',
	},
	container: {
		flex: 1,
		marginHorizontal: 16,
	},
	orderTxt: {
		textAlign: 'left',
		//paddingLeft: 16,
		paddingTop: 24,
		paddingBottom: 4,
		fontSize: 20,
		//: 600,
		color: 'black',
	},
	deliveryTxt: {
		fontFamily: myfonts.Medium,
		fontSize: 14,
		//: 500,
		lineHeight: 24,
		textAlign: 'left',
		color: myColors.slate600,
		marginLeft: 8,
	},
	saveBtn: {
		//width: Fill (361px)
		height: 48,
		paddingVertical: 12,
		paddingHorizontal: 24,
		borderRadius: 6,
		backgroundColor: theme_color,
		marginVertical: 8,
	},
	imgTxt: {
		fontFamily: myfonts.Medium,
		fontSize: 14,
		//: 500,
		lineHeight: 21,
		//textAlign: 'center',
		color: myColors.slate600,
		marginBottom: 8,
		marginLeft: 32,
		marginTop: 4,
	},
	chhoseTxt: {
		fontFamily: myfonts.Bold,
		fontSize: 12,
		//: 500,
		lineHeight: 18,
		textAlign: 'left',
		color: myColors.slate700,
	},
	fileUpload: {
		height: 30,
		width: 100,
		paddingVertical: 6,
		paddingHorizontal: 16,
		borderRadius: 4,
		marginRight: 10,
		backgroundColor: '#EEF2FF',
	},
	inputSm: {
		// width: Fill (156.5px)
		height: 42,
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 6,
		borderWidth: 1,
		borderColor: myColors.slate200,
		marginVertical: 16,
	},

	sectionImg: {
		width: 18,
		height: 18,
		marginHorizontal: 8,
	},
	sectionTxt: {
		fontFamily: myfonts.Regular,
		fontSize: 16,
		//: 500,
		lineHeight: 24,
		textAlign: 'left',
		color: '#475569',
		marginTop: -4,
	},
	rowView: {
		height: 53,
		padding: 16,
		borderRadius: 6,
		marginBottom: 24,
		backgroundColor: myColors.clrWhite,
		flexDirection: 'row',
	},
	textarea: {
		paddingBottom: 100,
		paddingHorizontal: 16,
		borderRadius: 6,
		borderWidth: 1,
		marginBottom: 8,
		height: 146,
		borderColor: '#E2E8F0',
	},
	input: {
		height: 42,
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 6,
		borderWidth: 1,
		borderColor: myColors.slate200,
	},
	productName: {
		fontFamily: myfonts.Medium,
		fontSize: 16,
		//: 500,
		textAlign: 'left',
		color: myColors.slate600,
		marginBottom: 8,
	},
	countValueTxt: {
		minWidth: 40,
		fontFamily: myfonts.Medium,
		fontSize: 16,
		//: 500,
		textAlign: 'center',
		color: myColors.slate600,
	},
	editTxt: {
		textAlign: 'left',
		fontFamily: myfonts.Bold,
		fontSize: 22,
		//: 600,
		lineHeight: 33,
		marginBottom: 24,
		color: myColors.slate800,
		marginTop: 25,
		marginBottom: 12,
	},
	formView: {
		//width: Fixed (361px)
		//height: 1062,
		paddingHorizontal: 16,
		paddingTop: 16,
		borderRadius: 8,
		margin: 2,
		backgroundColor: myColors.clrWhite,
		marginBottom: 24,
	},
});
export default giftstyles;
